[package]
name = "purple-presage-backend"
version = "0.0.0"
edition = "2021"

[lib]
name = "purple_presage_backend"
path = "src/lib.rs"
crate-type = ["staticlib"]

# presage needs this, taken from https://github.com/whisperfish/presage/blob/4377bdb/Cargo.toml
[patch.crates-io]
curve25519-dalek = { git = 'https://github.com/signalapp/curve25519-dalek', tag = 'signal-curve25519-4.1.3' }

[dependencies]
presage = { git = "https://github.com/whisperfish/presage", rev = "4377bdb" }
presage-store-sled = { git = "https://github.com/whisperfish/presage", rev = "4377bdb" }
mime-sniffer = { git = "https://github.com/kamadorueda/rust-mime-sniffer"}
#stdint = "0.2" # TODO: find out how to use this for more reliable type widths
# these are taken from https://github.com/whisperfish/presage/blob/4377bdb/presage-cli/Cargo.toml
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
futures = "0.3"
mime_guess = "2.0"
hex = "0.4"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread", "io-std", "io-util"] }

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true  # Automatically strip symbols from the binary. Needs rust 1.59 or newer.
#opt-level = "z"  # Optimize for size.
#lto = true
#codegen-units = 1
