#![no_main]

mod bridge;
mod bridge_commands;
mod contacts;
mod core;
mod receive;
mod attachment;
mod send;
mod structs;

/*
bridge_structs generated by this call to bindgen:

bindgen src/c/presage.h --allowlist-type Message --allowlist-type Group --opaque-type PurpleAccount --opaque-type RustChannelPtr --opaque-type PurpleXfer --opaque-type PurpleRoomlist --no-layout-tests --no-doc-comments --constified-enum PurpleDebugLevel --constified-enum PurpleConnectionError --bitfield-enum PurpleMessageFlags --raw-line '#![allow(dead_code, non_camel_case_types)]' -- $(pkg-config -cflags glib-2.0 purple) | sed 's/\(PurpleConnectionError_\)\|\(PurpleDebugLevel_\)//g' > src/rust/src/bridge_structs.rs

and then some manual modifications since bindgen produces different results depending on version and/or operating system
*/
mod bridge_structs;
